//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AuctionService
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/WcfAuctionHouse")]
    public partial class Item : object
    {
        
        private string BidCustomNameField;
        
        private string BidCustomPhoneField;
        
        private decimal BidPriceField;
        
        private System.DateTime BidTimestampField;
        
        private string ItemDescriptionField;
        
        private int ItemNumberField;
        
        private decimal RatingPriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BidCustomName
        {
            get
            {
                return this.BidCustomNameField;
            }
            set
            {
                this.BidCustomNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BidCustomPhone
        {
            get
            {
                return this.BidCustomPhoneField;
            }
            set
            {
                this.BidCustomPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal BidPrice
        {
            get
            {
                return this.BidPriceField;
            }
            set
            {
                this.BidPriceField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime BidTimestamp
        {
            get
            {
                return this.BidTimestampField;
            }
            set
            {
                this.BidTimestampField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ItemDescription
        {
            get
            {
                return this.ItemDescriptionField;
            }
            set
            {
                this.ItemDescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemNumber
        {
            get
            {
                return this.ItemNumberField;
            }
            set
            {
                this.ItemNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal RatingPrice
        {
            get
            {
                return this.RatingPriceField;
            }
            set
            {
                this.RatingPriceField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Bid", Namespace="http://schemas.datacontract.org/2004/07/WcfAuctionHouse")]
    public partial class Bid : object
    {
        
        private string CustomNameField;
        
        private string CustomPhoneField;
        
        private int ItemNumberField;
        
        private decimal PriceField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomName
        {
            get
            {
                return this.CustomNameField;
            }
            set
            {
                this.CustomNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomPhone
        {
            get
            {
                return this.CustomPhoneField;
            }
            set
            {
                this.CustomPhoneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ItemNumber
        {
            get
            {
                return this.ItemNumberField;
            }
            set
            {
                this.ItemNumberField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal Price
        {
            get
            {
                return this.PriceField;
            }
            set
            {
                this.PriceField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AuctionService.IAuctionHouse")]
    public interface IAuctionHouse
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionHouse/GetAllAuctionItems", ReplyAction="http://tempuri.org/IAuctionHouse/GetAllAuctionItemsResponse")]
        System.Threading.Tasks.Task<AuctionService.Item[]> GetAllAuctionItemsAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionHouse/GetAuctionItem", ReplyAction="http://tempuri.org/IAuctionHouse/GetAuctionItemResponse")]
        System.Threading.Tasks.Task<AuctionService.Item> GetAuctionItemAsync(int ItemNumber);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAuctionHouse/Bid", ReplyAction="http://tempuri.org/IAuctionHouse/BidResponse")]
        System.Threading.Tasks.Task<bool> BidAsync(AuctionService.Bid bid);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public interface IAuctionHouseChannel : AuctionService.IAuctionHouse, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.5.0.0")]
    public partial class AuctionHouseClient : System.ServiceModel.ClientBase<AuctionService.IAuctionHouse>, AuctionService.IAuctionHouse
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuctionHouseClient() : 
                base(AuctionHouseClient.GetDefaultBinding(), AuctionHouseClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IAuctionHouse.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuctionHouseClient(EndpointConfiguration endpointConfiguration) : 
                base(AuctionHouseClient.GetBindingForEndpoint(endpointConfiguration), AuctionHouseClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuctionHouseClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuctionHouseClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuctionHouseClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuctionHouseClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuctionHouseClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<AuctionService.Item[]> GetAllAuctionItemsAsync()
        {
            return base.Channel.GetAllAuctionItemsAsync();
        }
        
        public System.Threading.Tasks.Task<AuctionService.Item> GetAuctionItemAsync(int ItemNumber)
        {
            return base.Channel.GetAuctionItemAsync(ItemNumber);
        }
        
        public System.Threading.Tasks.Task<bool> BidAsync(AuctionService.Bid bid)
        {
            return base.Channel.BidAsync(bid);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuctionHouse))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IAuctionHouse))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:52317/AuctionHouse.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AuctionHouseClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IAuctionHouse);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AuctionHouseClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IAuctionHouse);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IAuctionHouse,
        }
    }
}
